name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build release libraries
        run: |
          make MODE=release -j

      - name: Build debug libraries
        run: |
          make -C libft fclean
          make MODE=debug -j

      - name: Create tarball
        run: |
          mkdir -p ft_termcap-release
          
          cp -r include ft_termcap-release/
          cp -r src ft_termcap-release/
          cp Makefile ft_termcap-release/
          cp README.md ft_termcap-release/
          cp LICENSE ft_termcap-release/
          
          cp libft_termcap.a ft_termcap-release/
          cp libft_termcap.so ft_termcap-release/
          cp libft_termcap_debug.a ft_termcap-release/
          cp libft_termcap_debug.so ft_termcap-release/

          tar -czf ft_termcap-${GITHUB_REF#refs/tags/}.tar.gz ft_termcap-release/

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -n "$PREVIOUS_TAG" ]; then
            echo "## Changes since $PREVIOUS_TAG" > CHANGELOG.md
            git log --pretty=format:"- %s (%h)" $PREVIOUS_TAG..HEAD >> CHANGELOG.md
          else
            echo "## Initial Release" > CHANGELOG.md
            git log --pretty=format:"- %s (%h)" >> CHANGELOG.md
          fi

          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ft_termcap-${{ github.ref_name }}.tar.gz
            libft_termcap.a
            libft_termcap.so
            libft_termcap_debug.a
            libft_termcap_debug.so
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-release:
      runs-on: ubuntu-latest
      needs: create-release

      steps:
        - name: Download release asset
          run: |
            curl -L -o ft_termcap-release.tar.gz \
              "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/ft_termcap-${{ github.ref_name }}.tar.gz"

        - name: Test release package
          run: |
            tar -xzf ft_termcap-release.tar.gz
            cd ft_termcap-release

            test -f libft_termcap.a
            test -f libft_termcap.so
            test -f libft_termcap_debug.a
            test -f libft_termcap_debug.so
            test -d include
            test -f Makefile

            echo "✅ Release package validation successful!"
